CREATE TABLE POST 
(
  ID NUMBER NOT NULL 
, TITLE VARCHAR2(20) NOT NULL 
, DESCRIPTION VARCHAR2(550) NOT NULL 
, STATUS NUMBER DEFAULT 1 
, CONSTRAINT POST_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE POST_SEQ;

CREATE TRIGGER POST_TRG 
BEFORE INSERT ON POST 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT POST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
